'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CarFront, Plus } from 'lucide-react';
type Quote = { id:string; quote_number:string; status:string; payment_status:string; total:number; created_at:string; customers?:{first_name?:string;last_name?:string}|null; leads?:{vehicle?:{year?:string;makeModel?:string}}|null };
type Lead = { id:string; vehicle:{year?:string;makeModel?:string}|null; estimate:{minimum?:number;maximum?:number}|null };
type QuoteResponse = { data:Quote[]; nextCursor:string|null; hasMore:boolean };
type LeadResponse = { data:Lead[]; nextCursor:string|null; hasMore:boolean };
export default function QuotesPage(){
 const [quotes,setQuotes]=useState<Quote[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [leadId,setLeadId]=useState('');const [price,setPrice]=useState('');const [notes,setNotes]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [quoteCursor,setQuoteCursor]=useState<string|null>(null);const [hasMoreQuotes,setHasMoreQuotes]=useState(true);const [loading,setLoading]=useState(true);const [loadingMore,setLoadingMore]=useState(false);
 const selectedLead=useMemo(()=>leads.find(lead=>lead.id===leadId)??null,[leads,leadId]);
 const minimum=selectedLead?.estimate?.minimum; const maximum=selectedLead?.estimate?.maximum;
 function handleLeadChange(next:string){setLeadId(next);const lead=leads.find(item=>item.id===next);const suggested=lead?.estimate?.maximum??lead?.estimate?.minimum;setPrice(suggested!=null?String(suggested):'');setMessage('');}
 async function loadQuotes(cursor:string|null=null,append=false){const params=new URLSearchParams({limit:'50'});if(cursor)params.set('cursor',cursor);const response=await fetch('/api/dashboard/quotes?'+params.toString(),{cache:'no-store'});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error||'Unable to load quotes.');const page=result as QuoteResponse;setQuotes(current=>append?[...current,...page.data]:page.data);setQuoteCursor(page.nextCursor);setHasMoreQuotes(page.hasMore);}
 async function loadLeads(){const response=await fetch('/api/dashboard/leads?limit=100',{cache:'no-store'});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error||'Unable to load leads.');setLeads((result as LeadResponse).data);}
 useEffect(()=>{void Promise.all([loadQuotes(),loadLeads()]).catch(error=>setMessage(error instanceof Error?error.message:'Unable to load quotes.')).finally(()=>setLoading(false))},[]);
 async function create(event:FormEvent){event.preventDefault();setMessage('');const amount=Number(price);if(!Number.isFinite(amount)||amount<0){setMessage('Enter a valid price.');return;}if(minimum!=null&&amount<minimum){setMessage('The quote price cannot be below the service minimum.');return;}if(maximum!=null&&amount>maximum){setMessage('The quote price cannot be above the service maximum.');return;}setBusy(true);const response=await fetch('/api/dashboard/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadId,amount,notes})});const result=await response.json().catch(()=>null);setMessage(response.ok?'Draft quote created.':result?.error??'Unable to create quote.');if(response.ok){setLeadId('');setPrice('');setNotes('');setQuoteCursor(null);setHasMoreQuotes(true);await loadQuotes(null,false)}setBusy(false)}
 async function loadMoreQuotes(){if(!quoteCursor||loadingMore)return;setLoadingMore(true);try{await loadQuotes(quoteCursor,true)}catch{setMessage('Unable to load more quotes.')}finally{setLoadingMore(false)}}
 async function updateStatus(id:string,status:string){await fetch('/api/dashboard/quotes/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await loadQuotes(null,false)}
 async function shareQuote(id:string){const response=await fetch('/api/dashboard/quotes/'+id+'/share',{method:'POST'});const result=await response.json().catch(()=>null);if(response.ok&&result?.url){try{await navigator.clipboard.writeText(result.url);setMessage('Secure quote link copied.')}catch{setMessage(result.url)}}else setMessage(result?.error??'Unable to create quote link.')}
 async function startPayment(id:string){setMessage('Opening secure Stripe checkout...');const response=await fetch('/api/dashboard/quotes/'+id+'/checkout',{method:'POST'});const result=await response.json().catch(()=>null);if(response.ok&&result?.url)window.location.assign(result.url);else setMessage(result?.error??'Unable to start payment.')}
 return <section className="dashboard-main"><Link href="/dashboard" className="button-secondary"><ArrowLeft size={15}/> Back to overview</Link>
 <div className="dash-header" style={{marginTop:34}}><div><span className="mono eyebrow">Revenue</span><h1>Quotes</h1><p>Create, send, and track quote status from qualified leads.</p></div></div>
 <form className="empty-state" onSubmit={create}><h2>Create a draft quote</h2><label className="field"><span>Lead</span><select value={leadId} onChange={event=>handleLeadChange(event.target.value)} required><option value="">Choose a lead</option>{leads.map(lead=><option value={lead.id} key={lead.id}>{lead.vehicle?.year??'Vehicle'} {lead.vehicle?.makeModel??'request'}</option>)}</select></label><label className="field"><span>Price to charge</span><input type="number" inputMode="decimal" min={minimum??0} max={maximum??undefined} step="0.01" value={price} onChange={event=>setPrice(event.target.value)} placeholder={minimum!=null||maximum!=null?`${minimum??0} - ${maximum??minimum??0}`:"Enter price"} required disabled={!leadId}/>{leadId&&(minimum!=null||maximum!=null)&&<small>Service range: ${minimum??0} – ${maximum??minimum??0}. Choose the exact amount for this quote.</small>}</label><label className="field"><span>Notes</span><textarea rows={3} value={notes} onChange={event=>setNotes(event.target.value)}/></label>{message&&<p role="status" className="auth-message">{message}</p>}<button className="button-primary" type="submit" disabled={busy}><Plus size={15}/> {busy?'Creating...':'Create draft'}</button></form>
 {loading?<div className="loading-skeleton-list" aria-label="Loading quotes"><div/><div/><div/><div/></div>:quotes.length===0?<div className="empty-state"><div className="empty-icon"><CarFront size={22}/></div><h2>No quotes yet.</h2><p>Create a draft from a lead to begin the quote lifecycle.</p></div>:<div className="lead-list">{quotes.map(quote=><div className="lead-card" key={quote.id}><div><strong>{quote.quote_number}</strong><span>{quote.customers?(quote.customers.first_name??'')+' '+(quote.customers.last_name??''):'Customer'} · ${quote.total}</span><small>Payment: {quote.payment_status}</small></div><div className="lead-card-right"><select value={quote.status} onChange={event=>void updateStatus(quote.id,event.target.value)}><option value="draft">Draft</option><option value="sent">Sent</option><option value="viewed">Viewed</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="expired">Expired</option></select>{quote.status!=='declined'&&quote.status!=='expired'&&<button className="button-secondary" type="button" onClick={()=>void shareQuote(quote.id)}>Share secure link</button>}{quote.status==='accepted'&&quote.payment_status!=='paid'&&<button className="button-secondary" type="button" onClick={()=>void startPayment(quote.id)}>Pay securely</button>}</div></div>)}</div>}
 {!loading&&!message&&hasMoreQuotes&&<div className="load-more"><button className="button-secondary" type="button" onClick={()=>void loadMoreQuotes()} disabled={loadingMore}>{loadingMore?'Loading…':'Load more quotes'}</button></div>}
 </section>;
}