import { ArrowRight, Check, ChevronDown, Sparkles } from 'lucide-react';

const steps = [
  ['01', 'Set your prices', 'Build a menu of services and adjustments that match how your shop actually quotes.'],
  ['02', 'Share your link', 'Send one polished intake link from your bio, inbox, or Google Business profile.'],
  ['03', 'Close the work', 'Get a clean lead with photos, vehicle details, and a price range worth replying to.'],
];

export default function Home() {
  return <main>
    <header className="shell nav"><a href="/" className="brand"><span className="brand-mark">DF</span> detailflow</a><nav className="nav-links"><a href="#how">How it works</a><a href="#product">Product</a><a href="#pricing">Pricing</a><a href="/quote/demo-detailing" className="nav-cta">Try the quote flow <ArrowRight size={15}/></a></nav></header>
    <section className="shell hero"><div><div className="kicker"><span/> for detailers who do good work</div><h1>Turn “how much?” into booked work.</h1><p className="hero-copy">DetailFlow gives every inquiry a clear next step. Customers share their vehicle, photos, and needs. You get a structured lead you can actually quote.</p><div className="hero-actions"><a className="button-primary" href="/quote/demo-detailing">Build your quote flow <ArrowRight size={16}/></a><a className="button-secondary" href="#how">See how it works</a></div><div className="hero-note">No credit card required · Set up in 10 minutes</div></div><div className="hero-visual"><div className="hero-photo"/><div className="floating-card"><div className="floating-card-top"><span>New lead · 2 min ago</span><span className="status"><i/> ready</span></div><h3>2021 Porsche Macan</h3><p>Full detail · Moderate interior · 8 photos attached</p></div></div></section>
    <section id="how" className="shell section"><div className="section-head"><div><div className="kicker"><span/> the simple loop</div><h2>Less back-and-forth. More work on the calendar.</h2></div><p className="section-intro">The whole experience is designed around the moment a customer asks for a price.</p></div><div className="steps">{steps.map(([n,t,d]) => <article className="step" key={n}><span className="step-num">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="product" className="product-band"><div className="shell product-grid"><div><div className="kicker"><span/> your new front desk</div><h2>A clearer picture of every job.</h2><p>See the vehicle, the condition, the requested service, and the customer’s contact details in one place. AI can flag visible issues, but your pricing rules stay in charge.</p><a className="button-secondary" href="/quote/demo-detailing" style={{marginTop:20,borderColor:'#769887',color:'#f8f4e9'}}>Preview the customer flow <ArrowRight size={15}/></a></div><div className="dashboard"><div className="dash-top"><span>DetailFlow / Overview</span><span>Tuesday, Jun 18</span></div><div className="dash-body"><div className="dash-side"><strong>Overview</strong><div>Leads</div><div>Quotes</div><div>Services</div><div>Business</div></div><div className="dash-content"><h3>Good morning, Jordan.</h3><div className="metric-row"><div className="metric"><small>NEW LEADS</small><b>18</b></div><div className="metric"><small>QUOTE RATE</small><b>64%</b></div><div className="metric"><small>PIPELINE</small><b>$4.2k</b></div></div><div className="lead-row"><b>2021 Porsche Macan</b><span>Full detail · $320–380</span></div><div className="lead-row"><b>2018 Ford F-150</b><span>Interior · $180–220</span></div><div className="lead-row"><b>2023 Tesla Model Y</b><span>Ceramic · $850–1.1k</span></div></div></div></div></div></section>
    <section id="pricing" className="shell section"><div className="section-head"><div><div className="kicker"><span/> straightforward pricing</div><h2>Start small. Grow when the leads do.</h2></div><p className="section-intro">Everything you need to replace scattered DMs with a better intake process.</p></div><div className="pricing"><div className="price-card"><h3>Starter</h3><div className="price">$0 <small>/ month</small></div><p>For getting your first quote link in the wild.</p><div className="mono" style={{fontSize:11,color:'#747a75'}}><Check size={13}/> 5 leads per month<br/><Check size={13}/> Quote link and services<br/><Check size={13}/> Email notifications</div><a className="button-primary" href="/quote/demo-detailing">Start free <ArrowRight size={15}/></a></div><div className="price-card featured"><h3>Pro <Sparkles size={16} style={{verticalAlign:'middle'}}/></h3><div className="price">$19 <small>/ month</small></div><p>For detailers ready to make intake a competitive edge.</p><div className="mono" style={{fontSize:11,color:'#5c5230'}}><Check size={13}/> Unlimited leads<br/><Check size={13}/> AI photo assessment<br/><Check size={13}/> Custom branding and analytics</div><a className="button-primary" href="/quote/demo-detailing">Choose Pro <ArrowRight size={15}/></a></div></div></section>
    <section className="shell section faq"><div><div className="kicker"><span/> questions, answered</div><h2>Good work deserves a good first impression.</h2></div><div><div className="faq-item">Does DetailFlow set my prices? <span><ChevronDown size={17}/></span></div><div className="faq-item">Can customers use it on their phone? <span><ChevronDown size={17}/></span></div><div className="faq-item">What happens when AI is unsure? <span><ChevronDown size={17}/></span></div></div></section>
    <footer className="shell footer"><a className="brand" href="/"><span className="brand-mark">DF</span> detailflow</a><span>Built for the people behind the cleanest cars.</span><span>© 2026 DetailFlow</span></footer>
  </main>;
}
