import { ArrowRight, Check, ChevronDown, Sparkles } from 'lucide-react';

const steps = [
  ['01', 'Set your prices', 'Build a menu of services and adjustments that match how your shop actually quotes.'],
  ['02', 'Share your link', 'Send one polished intake link from your bio, inbox, or Google Business profile.'],
  ['03', 'Close the work', 'Get a clean lead with photos, vehicle details, and a price range worth replying to.'],
];

export default function Home() {
  return <main>
  <header className="shell nav"><a href="/" className="brand"><span className="brand-mark">DF</span> detailflow</a><nav className="nav-links"><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="/login" className="nav-cta">I have a business <ArrowRight size={15} /></a></nav></header>
  <section className="shell hero"><div><div className="kicker"><span /> for detailing businesses</div><h1>Turn every inquiry into a clear next step.</h1><p className="hero-copy">DetailFlow gives your customers a structured way to request a quote and gives your business one place to manage the work.</p><div className="hero-actions"><a className="button-primary" href="/quote">Request a quote <ArrowRight size={16} /></a><a className="button-secondary" href="/login">I own a business</a></div><div className="hero-note">Create your workspace with your own business information.</div></div><div className="hero-visual"><div className="hero-photo" /><div className="floating-card"><div className="floating-card-top"><span>Your public quote flow</span><span className="status"><i /> live</span></div><h3>Real business data</h3><p>Services, contact details, photos, and customer requests in one flow.</p></div></div></section>
    <section id="how" className="shell section"><div className="section-head"><div><div className="kicker"><span/> the simple loop</div><h2>Less back-and-forth. More work on the calendar.</h2></div><p className="section-intro">The whole experience is designed around the moment a customer asks for a price.</p></div><div className="steps">{steps.map(([n,t,d]) => <article className="step" key={n}><span className="step-num">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="how" className="shell section"><div className="section-head"><div><div className="kicker"><span /> the simple loop</div><h2>Less back-and-forth. More work on the calendar.</h2></div><p className="section-intro">Set up the information your customers need, then let the app collect complete requests for you.</p></div><div className="steps">{steps.map(([number, title, description]) => <article className="step" key={number}><span className="step-num">{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="pricing" className="shell section"><div className="section-head"><div><div className="kicker"><span/> straightforward pricing</div><h2>Start small. Grow when the leads do.</h2></div><p className="section-intro">Everything you need to replace scattered DMs with a better intake process.</p></div><div className="pricing"><div className="price-card"><h3>Starter</h3><div className="price">$0 <small>/ month</small></div><p>For getting your first quote link in the wild.</p><div className="mono" style={{fontSize:11,color:'#747a75'}}><Check size={13}/> 5 leads per month<br/><Check size={13}/> Quote link and services<br/><Check size={13}/> Email notifications</div><a className="button-primary" href="/quote">Start free <ArrowRight size={15}/></a></div><div className="price-card featured"><h3>Pro <Sparkles size={16} style={{verticalAlign:'middle'}}/></h3><div className="price">$19 <small>/ month</small></div><p>For detailers ready to make intake a competitive edge.</p><div className="mono" style={{fontSize:11,color:'#5c5230'}}><Check size={13}/> Unlimited leads<br/><Check size={13}/> AI photo assessment<br/><Check size={13}/> Custom branding and analytics</div><a className="button-primary" href="/login">Choose Pro <ArrowRight size={15}/></a></div></div></section>
    <section id="pricing" className="shell section"><div className="section-head"><div><div className="kicker"><span /> straightforward pricing</div><h2>Start with the tools you need.</h2></div><p className="section-intro">Create an account and configure your workspace before sharing it with customers.</p></div><div className="pricing"><div className="price-card"><h3>Workspace</h3><div className="price">Free</div><p>Set up your business profile and public quote flow.</p><div className="mono" style={{ fontSize: 11, color: '#747a75' }}><Check size={13} /> Business profile<br /><Check size={13} /> Public quote link<br /><Check size={13} /> Lead inbox</div><a className="button-primary" href="/login">Create workspace <ArrowRight size={15} /></a></div></div></section>
    <section className="shell section faq"><div><div className="kicker"><span /> questions, answered</div><h2>Built around the information that matters.</h2></div><div><div className="faq-item">Can I use my own services and prices? <span><ChevronDown size={17} /></span></div><div className="faq-item">Can customers use the quote flow on mobile? <span><ChevronDown size={17} /></span></div><div className="faq-item">Where do submitted requests appear? <span><ChevronDown size={17} /></span></div></div></section>
    <footer className="shell footer"><a className="brand" href="/"><span className="brand-mark">DF</span> detailflow</a><span>Built for detailing businesses.</span><span>© 2026 DetailFlow</span></footer>
  </main>;
}
