import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { getAppUrl, getStripe } from '@/lib/stripe';
import Stripe from 'stripe';
export const runtime='nodejs';
const planSchema=z.object({plan:z.enum(['pro','business'])});
async function ctx(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',user.id).limit(1).maybeSingle();return m?{supabase,user,m}:null;}
function priceFor(plan:'pro'|'business'){return plan==='business'?process.env.STRIPE_BUSINESS_PRICE_ID:process.env.STRIPE_PRO_PRICE_ID;}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:'Not authenticated.'},{status:401});const {data:b}=await c.supabase.from('businesses').select('id,name,plan,stripe_customer_id,stripe_subscription_id,subscription_status,stripe_connected_account_id,stripe_connect_status,stripe_charges_enabled,stripe_payouts_enabled,stripe_details_submitted').eq('id',c.m.business_id).single();if(!b)return NextResponse.json({error:'Workspace not found.'},{status:404});let prices:{pro:number|null;business:number|null}={pro:null,business:null};try{const stripe=getStripe();const ids=[['pro',process.env.STRIPE_PRO_PRICE_ID],['business',process.env.STRIPE_BUSINESS_PRICE_ID]] as const;for(const [key,id] of ids){if(!id)continue;const price=(await stripe.prices.retrieve(id)) as unknown as Stripe.Price;prices[key]=price.unit_amount===null?null:Number(price.unit_amount)/100;}}catch(error){console.error('Unable to load Stripe price display:',error instanceof Error?error.message:'unknown');}return NextResponse.json({...b,prices});}
export async function POST(request:Request){const c=await ctx();if(!c)return NextResponse.json({error:'Not authenticated.'},{status:401});if(c.m.role!=='owner')return NextResponse.json({error:'Only the owner can manage billing.'},{status:403});const parsed=planSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Choose a valid membership plan.'},{status:400});const price=priceFor(parsed.data.plan);if(!price)return NextResponse.json({error:`Stripe price for ${parsed.data.plan} is not configured.`},{status:503});const {data:b}=await c.supabase.from('businesses').select('id,name,plan,stripe_customer_id,stripe_subscription_id').eq('id',c.m.business_id).single();if(!b)return NextResponse.json({error:'Workspace not found.'},{status:404});if(b.plan===parsed.data.plan)return NextResponse.json({error:`This workspace is already on ${parsed.data.plan}.`},{status:409});try{const stripe=getStripe();if(b.stripe_subscription_id){const subscription=(await stripe.subscriptions.retrieve(b.stripe_subscription_id)) as unknown as Stripe.Subscription;const item=subscription.items.data[0];if(item){const updated=(await stripe.subscriptions.update(b.stripe_subscription_id,{items:[{id:item.id,price}],proration_behavior:'create_prorations',metadata:{businessId:c.m.business_id,plan:parsed.data.plan}})) as unknown as Stripe.Subscription;await c.supabase.from('subscriptions').update({stripe_price_id:price,plan:parsed.data.plan,status:updated.status,cancel_at_period_end:updated.cancel_at_period_end,updated_at:new Date().toISOString()}).eq('business_id',c.m.business_id);return NextResponse.json({changed:true,plan:parsed.data.plan});}}const session=(await stripe.checkout.sessions.create({mode:'subscription',line_items:[{price,quantity:1}],customer:b.stripe_customer_id||undefined,customer_email:b.stripe_customer_id?undefined:c.user.email||undefined,metadata:{businessId:c.m.business_id,plan:parsed.data.plan},subscription_data:{metadata:{businessId:c.m.business_id,plan:parsed.data.plan}},client_reference_id:c.m.business_id,success_url:`${getAppUrl()}/dashboard/settings?billing=success`,cancel_url:`${getAppUrl()}/dashboard/settings?billing=cancelled`},{idempotencyKey:`subscription:${c.m.business_id}:${parsed.data.plan}:${price}`})) as unknown as Stripe.Checkout.Session;return NextResponse.json({url:session.url});}catch(error){console.error('Subscription checkout failed:',error instanceof Error?error.message:'unknown');return NextResponse.json({error:'Unable to start membership checkout. Check Stripe configuration.'},{status:502});}}
export async function PATCH(){const c=await ctx();if(!c)return NextResponse.json({error:'Not authenticated.'},{status:401});if(c.m.role!=='owner')return NextResponse.json({error:'Only the owner can manage billing.'},{status:403});const {data:b}=await c.supabase.from('businesses').select('stripe_customer_id').eq('id',c.m.business_id).single();if(!b?.stripe_customer_id)return NextResponse.json({error:'No Stripe customer exists yet.'},{status:400});try{const session=(await getStripe().billingPortal.sessions.create({customer:b.stripe_customer_id,return_url:`${getAppUrl()}/dashboard/settings`})) as unknown as Stripe.BillingPortal.Session;return NextResponse.json({url:session.url});}catch{return NextResponse.json({error:'Unable to open the Stripe billing portal.'},{status:502});}}
