'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Plus, Save, Archive } from 'lucide-react';

type Service = { id: string; name: string; description: string | null; pricing_type: string; minimum_price: number; maximum_price: number; active: boolean; requires_photos: boolean };
type FormState = { name: string; description: string; pricingType: 'fixed' | 'range' | 'starting_at' | 'custom'; minimumPrice: string; maximumPrice: string; requiresPhotos: boolean };
const emptyForm: FormState = { name: '', description: '', pricingType: 'range', minimumPrice: '0', maximumPrice: '0', requiresPhotos: false };

export default function ServicesPage() {
  const [services, setServices] = useState<Service[]>([]);
  const [form, setForm] = useState<FormState>(emptyForm);
  const [editing, setEditing] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);

  async function load() { const response = await fetch('/api/dashboard/services'); if (response.ok) setServices(await response.json()); else setMessage('Unable to load services.'); }
  useEffect(() => { void load(); }, []);
  function update(key: keyof FormState, value: string | boolean) { setForm((current) => ({ ...current, [key]: value })); }
  function edit(service: Service) { setEditing(service.id); setForm({ name: service.name, description: service.description ?? '', pricingType: service.pricing_type as FormState['pricingType'], minimumPrice: String(service.minimum_price), maximumPrice: String(service.maximum_price), requiresPhotos: service.requires_photos }); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const response = await fetch(editing ? `/api/dashboard/services/${editing}` : '/api/dashboard/services', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json().catch(() => null); if (!response.ok) setMessage(result?.error ?? 'Unable to save service.'); else { setForm(emptyForm); setEditing(null); await load(); } setBusy(false); }
  async function archive(id: string) { const response = await fetch(`/api/dashboard/services/${id}`, { method: 'DELETE' }); if (!response.ok) setMessage('Unable to archive service.'); else await load(); }

  return <section className="dashboard-main"><Link href="/dashboard" className="button-secondary"><ArrowLeft size={15} /> Back to overview</Link><div className="dash-header" style={{ marginTop: 34 }}><div><span className="mono eyebrow">Workspace</span><h1>Services</h1><p>Control what customers can request and how estimates are calculated.</p></div></div><div className="dashboard-content-grid"><form className="empty-state" onSubmit={submit}><h2>{editing ? 'Edit service' : 'Add a service'}</h2><div className="field"><label htmlFor="serviceName">Name</label><input id="serviceName" value={form.name} onChange={(event) => update('name', event.target.value)} required /></div><div className="field"><label htmlFor="serviceDescription">Description</label><textarea id="serviceDescription" value={form.description} onChange={(event) => update('description', event.target.value)} rows={3} /></div><div className="form-grid"><div className="field"><label htmlFor="minimumPrice">Minimum</label><input id="minimumPrice" type="number" min="0" step="0.01" value={form.minimumPrice} onChange={(event) => update('minimumPrice', event.target.value)} required /></div><div className="field"><label htmlFor="maximumPrice">Maximum</label><input id="maximumPrice" type="number" min="0" step="0.01" value={form.maximumPrice} onChange={(event) => update('maximumPrice', event.target.value)} required /></div></div><label className="field"><span>Pricing type</span><select value={form.pricingType} onChange={(event) => update('pricingType', event.target.value)}><option value="fixed">Fixed</option><option value="range">Range</option><option value="starting_at">Starting at</option><option value="custom">Custom</option></select></label><label className="field"><span><input type="checkbox" checked={form.requiresPhotos} onChange={(event) => update('requiresPhotos', event.target.checked)} /> Requires photos</span></label>{message && <p role="alert" className="auth-message">{message}</p>}<button className="button-primary" type="submit" disabled={busy}>{editing ? <Save size={15} /> : <Plus size={15} />}{busy ? 'Saving...' : editing ? 'Save changes' : 'Add service'}</button>{editing && <button className="button-secondary" type="button" onClick={() => { setEditing(null); setForm(emptyForm); }}>Cancel</button>}</form><div className="lead-list">{services.length === 0 ? <div className="empty-state"><h2>No services yet.</h2><p>Add the first service to activate your public quote flow.</p></div> : services.map((service) => <div className="lead-card" key={service.id}><div><strong>{service.name}</strong><span>${service.minimum_price} - ${service.maximum_price} · {service.active ? 'Active' : 'Archived'}</span></div><div className="lead-card-right"><button className="button-secondary" type="button" onClick={() => edit(service)}>Edit</button><button className="button-secondary" type="button" onClick={() => void archive(service.id)}><Archive size={14} /></button></div></div>)}</div></div></section>;
}
